apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  labels:
    app: webapi
    tier: api
spec:
  type: NodePort
  selector:
    tier: api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000