apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: webapi
    tier: api
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: api
  template:
    metadata:
      labels:
        tier: api
    spec:
      containers:
      - name: webapi
        image: badokun/webapp:v2
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m" # 20% of CPU
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

# k get deployments --show-labels
# k scale deployment api --replicas=4
# k delete deployment api

# k describe deployment api
# k get deployments -l tier=api --> find deployment based on label

# k expose deployment api --type="LoadBalancer" --port=80 --target-port=80
# k expose rc api-b84766bcc --port=80 --target-port=80 --name=webapp-service --type=LoadBalancer