apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
  labels:
    app: webapi
    tier: api
spec:
  type: LoadBalancer
  selector:
    tier: api
  ports:
    - name: "80"
      port: 80
      targetPort: 80