apiVersion: v1
kind: Service
metadata:
  name: api-clusterip
  labels:
    app: webapi
    tier: api
spec:
  selector:
    tier: api
  ports:
    - port: 8080
      targetPort: 80

# k exec api-858bc69987-6vqx9 -it sh
# curl http://api-clusterip:8080/ping   