apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque
data:
  api-key: YXJleW91b3V0b2Z5b3VybWluZA==

# dont use this method since the secret is just base64 encoded
# https://www.base64encode.org/

# Better way of storing secret
# k create secret generic webapp-secrets --from-literal=api-key=areyououtofyourmind