apiVersion: v1
kind: Service
metadata:
  name: api-external-service
  labels:
    app: webapi
    tier: api
spec:
  type: ExternalName
  externalName: www.google.com

# k exec api-858bc69987-6vqx9 -it sh
# curl http://api-external-service