apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 2
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1
    ports:
    - containerPort: 80

    
# k describe pod my-nginx
# k exec my-nginx -it sh